**Vector operations**

In [2]:
#importing numpy library
import numpy as np

In [3]:
#creating arrays
u = np.array([1, 8, 5, 3])
v = np.array([6, 8, 4, 2])
print(u)
print(v)

[1 8 5 3]
[6 8 4 2]


In [4]:
#addition
u + v

array([ 7, 16,  9,  5])

In [5]:
#subtraction
v - u

array([ 5,  0, -1, -1])

In [6]:
#scalar multiplication
10 * v

array([60, 80, 40, 20])

**Vector - vector multiplication**

In [7]:
#in pyhton
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = v.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    return result
    

In [8]:
vector_vector_multiplication(u,v)

np.float64(96.0)

In [9]:
#using numpy
u.dot(v)

np.int64(96)

**Matrix - vector multiplication**

In [10]:
#creating a matrix U
U = np.array([
        [2, 4, 5, 6],
        [1, 2, 1, 2],
        [3, 1, 2, 1],
    ])
np.shape(U)

(3, 4)

In [15]:
#in python
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result

In [16]:
matrix_vector_multiplication(U,v)

array([76., 30., 36.])

In [17]:
#using numpy
U.dot(v)

array([76, 30, 36])

**Matrix - Matrix multiplication**

In [18]:
#creating matrix V
V = np.array([
     [1, 1, 2],
     [0, 0.5, 1], 
     [0, 2, 1],
     [2, 1, 0],
 ])
np.shape(V)

(4, 3)

In [19]:
#using python
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi

    return result

In [20]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
#using numpy
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

**Identity Matrix**

In [24]:
#to create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Inverse of a matrix**

In [26]:
#creating a square matrix
a = np.array([
    [4, 8, 6, 9],
    [7, 4, 3, 0],
    [9, 8, 0, 1],
    [6, 4, 9, 7]
])
print(a)

[[4 8 6 9]
 [7 4 3 0]
 [9 8 0 1]
 [6 4 9 7]]


In [27]:
#to find inverse of a matrix
np.linalg.inv(a)

array([[-0.30769231, -0.42307692,  0.34615385,  0.34615385],
       [ 0.375     ,  0.5625    , -0.3125    , -0.4375    ],
       [ 0.21794872,  0.57051282, -0.39102564, -0.22435897],
       [-0.23076923, -0.69230769,  0.38461538,  0.38461538]])