**Zoomcamp Numpy Exercise Practice**

**Creating Arrays**

In [1]:
#importing numpy
import numpy as np

In [2]:
#creating an array of zeroes
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#creating an array of ones
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#creating an array of any number
np.full(11, 100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [5]:
#making an array from python list
a = np.array([12, 45, 64, 21, 78, 45])
print(a)

[12 45 64 21 78 45]


In [6]:
#to access an element from list
a[3]

np.int64(21)

In [7]:
#to change an element in list 
a[2] = 88

In [8]:
a[2]

np.int64(88)

In [9]:
#to create a range of a number
np.arange(40, 51)

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
#to create an array filled with numbers and elenly spaced between first and second parameter
np.linspace(100, 900, 20)

array([100.        , 142.10526316, 184.21052632, 226.31578947,
       268.42105263, 310.52631579, 352.63157895, 394.73684211,
       436.84210526, 478.94736842, 521.05263158, 563.15789474,
       605.26315789, 647.36842105, 689.47368421, 731.57894737,
       773.68421053, 815.78947368, 857.89473684, 900.        ])

**Multi-dimensional arrays**

In [13]:
#to create multi-dimensional array of zeroes
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
#to create multi-dimensional array from list
b = np.array([
    [5, 7, 8, 9],
    [7, 5, 2, 1],
    [9, 3, 0, 6]
])
print(b)

[[5 7 8 9]
 [7 5 2 1]
 [9 3 0 6]]


In [15]:
#indexing in multi-dimensional array
b[1, 2]

np.int64(2)

In [16]:
#to get the whole row
b[1]

array([7, 5, 2, 1])

In [19]:
#to rewrite the entire row
b[2] = [9, 5, 2, 6]
b[2]

array([9, 5, 2, 6])

In [20]:
#to get the entire column
b[:, 0]

array([5, 7, 9])

In [22]:
#to rewrite the entire column
b[:, 0] = [4, 4, 4]
b[:, 0]

array([4, 4, 4])

**Randomly generated arrays**

In [23]:
#to create ararys of random numbers
np.random.rand(6,3)

array([[0.36404454, 0.60894863, 0.51410235],
       [0.96484435, 0.38956854, 0.28102157],
       [0.43432515, 0.39207296, 0.85601061],
       [0.13054701, 0.5534435 , 0.37045443],
       [0.34422656, 0.10557975, 0.17332278],
       [0.48040157, 0.4595805 , 0.28459662]])

In [24]:
#to get the result same everytime we run the code
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [26]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [27]:
#random normal(standard normal distribution)
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [28]:
#to generate random integer with a specific range
np.random.randint(low=100, high=900, size=(5,2))

array([[224, 728],
       [779, 295],
       [202, 872],
       [151, 459],
       [650, 645]], dtype=int32)

**Element-wise operations**

In [29]:
#creating an array
r = np.arange(11)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [30]:
#performing sum
r + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
#performing subtraction
r - 8

array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2])

In [32]:
#performing multiplication
r * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [33]:
r * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
#performing division
r/56

array([0.        , 0.01785714, 0.03571429, 0.05357143, 0.07142857,
       0.08928571, 0.10714286, 0.125     , 0.14285714, 0.16071429,
       0.17857143])

In [36]:
#performing all operators
100 * (r + 10)/ 200 - 20

array([-15. , -14.5, -14. , -13.5, -13. , -12.5, -12. , -11.5, -11. ,
       -10.5, -10. ])

In [40]:
#creating another array
s = np.arange(11, 22)
print(s)

[11 12 13 14 15 16 17 18 19 20 21]


In [41]:
#adding two arrays
print(r+s)

[11 13 15 17 19 21 23 25 27 29 31]


**Comparison operations**

In [42]:
#comparing array r
r > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [43]:
#comaparing two arrays
r < s

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
#to find the values which are true
r[r>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

**Summarizing operations**

In [46]:
#creating an array
np.random.seed(2)
k = np.random.randint(low=10, high=1000, size=(1,20))
print(k)

[[178 537 503 594 544 309 476  85 370 273 684 443 617 597 735  57 841 297
  740 414]]


In [48]:
#to find minimum from the array k
k.min()

np.int32(57)

In [49]:
#to find maximum from array k
k.max()

np.int32(841)

In [50]:
#to find sum of array k
k.sum()

np.int64(9294)

In [51]:
#to find standard deviation of array k
k.std()

np.float64(212.46013743759087)

In [52]:
#to find mean of array k
k.mean()

np.float64(464.7)